repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        require_serial: true
        exclude: ^{{ cookiecutter.__project_slug }}
      - id: check-toml
        name: check toml
        entry: check-toml
        language: system
        types: [toml]
      - id: darglint
        name: darglint
        entry: darglint
        language: system
        types: [python]
        stages: [manual]
      - id: isort
        name: isort
        entry: isort
        require_serial: true
        language: system
        types_or: [cython, pyi, python]
        args: ["--filter-files"]
      - id: pyupgrade
        name: pyupgrade
        description: Automatically upgrade syntax for newer versions.
        entry: pyupgrade
        language: system
        types: [python]
        args: [--py38-plus]

  - repo: https://github.com/PyCQA/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8
        types: [python]
        require_serial: true
        # args: [--darglint-ignore-regex, .*]
        additional_dependencies:
          - flake8-bugbear==22.9.23
          - flake8-comprehensions==3.10.0
          - flake8-simplify==0.19.3

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        name: check yaml
        stages: [commit, push, manual]
      - id: end-of-file-fixer
        name: end of file fixer
        stages: [commit, push, manual]
      - id: trailing-whitespace
        name: trim trailing whitespace
        stages: [commit, push, manual]
      - id: check-added-large-files
        name: check added large files
        stages: [commit, push, manual]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.0
    hooks:
      - id: prettier
